import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/elements/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="pt-16">
          {children}
          <a
            href="https://wa.me/573000000000"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed right-4 bottom-6 flex items-center gap-2 rounded-full bg-[#25D366] px-5 pb-3 pt-2 text-white font-medium shadow-lg hover:scale-105 transition-transform"
          >
            <img src="/whatsapp-3.svg" alt="WhatsApp" className="w-8 h-8" />
            <span className="text-base md:text-lg">Escríbenos</span>
          </a>
        </main>
      </body>
    </html>
  );
}
